port:  5000
markdown: kramdown
name: "Chicago Lobbyists Blog"
url: http://blog.chicagolobbyists.org
encoding: utf-8
timezone: America/Chicago
gems:
  - jekyll-redirect-from
permalink: pretty
paginate: 5